observeinc/aws-sam-apps

- cmd/forwarder/main.go
- cmd/subscriber/main.go
- handler/env.go
- handler/env_test.go
Setting a default in our env struct currently only affects the value being read into the struct. It is generally useful to have that value exporting back to the environment, in the case where other libraries source their configuration from the environment directly.
An existing usecase is where we modify the default for `AWS_MAX_ATTEMPTS`. The AWS SDK reads this environment variable directly when configuring the client.
> fix: export defaults to environment variables

- apps/forwarder/template.yaml
- cmd/forwarder/main.go
- handler/forwarder/config.go
- handler/forwarder/handler.go
- handler/forwarder/handler_test.go
- integration/tests/forwarder.tftest.hcl
- tracing/aws.go
- tracing/mux.go
- tracing/tracing.go
This commit adds OTEL tracing capabilities to the Forwarder lambda. I've so far left the subscriber lambda untouched, but this is the first step of moving the OTEL bits into a shared package.
The proposed code simplifies setup somewhat:
- we set the `OTEL_TRACES_EXPORTER` env var to `none` by default. This simplifies some of the intialization code we had prior.
- we instantiate a Tracer at `cmd`, and pass it into an instrumented Handler
- we explicitly pass `TracerProvider` where necessary rather than relying on global variables.
> feat(forwarder): add OTEL tracing

- .gitignore
- Makefile
- cmd/forwarder/main.go
- version/version.go
We want to set the version at build time. Unfortunately, the `sam build` command makes this slightly convoluted, given it executes `make build-${Resource}` without inheriting any of the variables passed into our original `make sam-build` call.
As a workaround, we stash the desired version in a file and source it back in. This is inherently race-y, since concurrent builds may overwite the file repeatedly. This risk should be fine for the time being, since we're always writing the same version value and we currently build serially.
> feat(forwarder): set version on build

- apps/logwriter/template.yaml
- cmd/subscriber/main.go
- handler/subscriber/config.go
- handler/subscriber/handler.go
- handler/subscriber/instrument.go
- handler/subscriber/instrument_test.go
- integration/tests/logwriter.tftest.hcl
This commit modifies the subscriber to reuse the same OTEL helpers as the forwarder.
We can eventually move all OTEL code out of `handler/subscriber`, but it's more effort than it is worth for now.
> refactor(subscriber): use shared tracing package

- integration/tests/metricstream.tftest.hcl
Surprisingly this was caught in CI out of nowhere:
```
│ Error: waiting for CloudFormation Stack (arn:aws:cloudformation:us-west-2:091720823232:stack/well-monarch-3b75b1bad4a9701d888aa07ec6c027eed549be6681f7a0fa5b2cc15e63e5c28896430d5d812226447072a657e699e6fb246a680f8b1f98e6d9e/da532300-fe7e-11ee-bdc8-06c2ef2a1519) create: failed to create CloudFormation stack, rollback requested (ROLLBACK_COMPLETE): ["The following resource(s) failed to create: [DeliveryStream]. Rollback requested by user." "User: arn:aws:sts::091720823232:assumed-role/well-monarch-3b75b1bad4a9701d888-20240419185846892400000001/AWSCloudFormation is not authorized to perform: firehose:TagDeliveryStream on resource: arn:aws:firehose:us-west-2:091720823232:deliverystream/well-monarch-3b75b1bad4a9701d888aa07ec6c027eed549be668 …
```
> fix(metricstream): update permissions

- handler/forwarder/config.go
- handler/forwarder/handler.go
- handler/forwarder/handler_test.go
- handler/forwarder/message.go
- handler/forwarder/message_test.go
- handler/forwarder/testdata/event.json
- handler/forwarder/testdata/multiple-records.json
Copying large objects can take a while when executing across regions. This commit ensures we handle each SQS record concurrently, which should be safe since:
- `s3:CopyObject` does not consume lambda resources, so we are not at risk of running out of memory / cpu
- our fan out factor is capped by our batch size on the SQS queue, which is quite small when compared to the AWS API limits.
Each SQS record itself may contain a list of files to copy. This list is still processed serially for now. In practice we do not use this capability yet.
> feat(forwarder): handle records concurrently

- apps/forwarder/template.yaml
- integration/tests/firehose.tftest.hcl
The duration of `CopyObject` depends on file size and source and destination region. In order to account for large files, we need to increase our lambda timeout value.
> fix(forwarder): increase timeout

- cmd/forwarder/main.go
- handler/forwarder/override/presets/infer/v1.yaml
- handler/forwarder/override/presets_test.go
- integration/tests/logwriter.tftest.hcl
- integration/tests/stack.tftest.hcl
In the case where no content type is set, we can try to infer based on the filename. We should also attempt inference when confronted with content types that don't signal what the type actually is (e.g. `binary/octet-stream`).
> feat(forwarder): add inference presets

- handler/forwarder/override/presets/aws/v1.yaml
- handler/forwarder/override/presets_test.go
- handler/forwarder/override/rule.go
We often don't have control of what is writing into a source bucket. As an example, AWS writes an `aws-programmatic-access-test-object` file with content-type `application/octet-stream`. Filename inference is not able to adequately detect that this is a simple text file, and in any case we don't even want to ingest it.
This commit adds the ability to add a content type override that disables forwarding for matches files. If a content type is set to `text/x-ignore`, we will not forward the file.
This is a dubious overloading of the content type field, but it is the most practical given our configuration constraints. We are currently surfacing content type overrides consistently in terraform and cloudformation. Adding a separate variable to capture what files should be forwarded would add …
> feat: introduce ability to ignore files

- apps/configsubscription/README.md
- apps/configsubscription/template.yaml
- apps/stack/template.yaml
- docs/configsubscription.md
- docs/stack.md
- integration/tests/configsubscription.tftest.hcl
- integration/tests/stack.tftest.hcl
When enabled, AWS Config emits events to EventBridge. This opens the opportunity to ingest AWS Config data without having to manually subscribe an S3 bucket (for config history, snapshot and oversized notifications) and SNS Topic (for change notifications).
We add a new parameter, `ConfigDeliveryBucketName`, which gates whether to attempt to ingest config data. When present:
- we add the bucket to the source bucket list for our forwarder
- we add an eventbridge rule to construct copy commands for the forwarder on successful config delivery
- we add an eventbridge rule to forward all Config events
> feat(stack): auto-subscribe to AWS Config

- handler/forwarder/s3http/client.go
- handler/forwarder/s3http/config.go
- handler/forwarder/s3http/internal/request/builder.go
- handler/forwarder/s3http/internal/request/handler.go
- handler/forwarder/s3http/internal/request/handler_test.go
When using HTTP legacy forwarder, set GZIP compression by default.
> feat(forwarder): support gzip compression

- Makefile
- apps/forwarder/template.yaml
- apps/stack/template.yaml
- docs/forwarder.md
- docs/stack.md
- integration/tests/forwarder.tftest.hcl
- integration/tests/forwarder_s3.tftest.hcl
- integration/tests/stack.tftest.hcl
- integration/variables.tf
This commit relaxes DataAccessPointArn as a required parameter for the Forwarder stack. The prior settings assumed the stack would always point at Filedrop. In practice, there can be usecases where an access point should not be assumed:
- if we point directly at an S3 bucket, for testing or aggregation purposes.
- if we point the forwarder towards an HTTP endpoint instead.
> fix(forwarder): relax DataAccessPointArn requirement

- apps/stack/template.yaml
We need to allow users to disable metrics collection by not providing URI.
> fix(stack): adjust validation for MetricStreamFilterURI

- handler/forwarder/s3http/client.go
- handler/forwarder/s3http/internal/decoders/cloudwatch.go
- handler/forwarder/s3http/internal/decoders/csv.go
- handler/forwarder/s3http/internal/decoders/decoder.go
- handler/forwarder/s3http/internal/decoders/decoder_test.go
- handler/forwarder/s3http/internal/decoders/json.go
- handler/forwarder/s3http/internal/decoders/text.go
- handler/forwarder/s3http/internal/decoders/wrapper.go
Simplify DecoderFactory by allowing caller to pass in parameters alongside io.Reader.
> refactor(forwarder): refactor DecoderFactory

- handler/forwarder/s3http/internal/batch/queue.go
- handler/forwarder/s3http/internal/batch/runner.go
- handler/forwarder/s3http/internal/request/builder.go
This commit reduces the amount of spam in error messages derived from HTTP request failures. Prior to this commit, a 401 would surface as:
```
failed to write messages: failed to process: failed to stream data: failed to consume: failed to upload: %w: unauthorized
```
The `%w` is a bug, while the excessive length can be handled by ditching error wrapping in some of the chain.
> fix(forwarder): reduce error wrapping

- handler/forwarder/s3http/internal/request/builder.go
We should retain query parameters for any URL provided to us.
> fix(forwarder): retain query parameters

- apps/forwarder/template.yaml
We want to specify a higher default if destination is HTTP.
We define all parameters as strings so as to be able to specify an empty string by default. This ensures we can safely update defaults later.
> fix(forwarder): adjust memory and timeout based on URI

- apps/forwarder/template.yaml
- docs/forwarder.md
Expose paramter to configure logging verbosity and dial down default value. Update documentation of forwarder parameters.
> fix(forwarder): add verbosity parameter

- apps/logwriter/template.yaml
- docs/forwarder.md
- docs/logwriter.md
- handler/forwarder/override/set.go
- integration/tests/logwriter.tftest.hcl
Same deal as with forwarder. Update the forwarder docs while we're at it.
> fix(logwriter): expose verbosity parameter

- handler/forwarder/s3http/client.go
We want to ignore empty files when submitting over HTTP, since they would produce no records even if the decoder supported an immediate EOF. Due to a limitation in the AWS SDK, we cannot disambiguate whether a file size is absent or 0 when processing an S3 bucket notification. Instead, we inspect the ContentLength of the S3 GetObject response.
This handling is not needed in the Filedrop case, since we handle empty files in the ingest pipeline, and we only execute a single CopyObject command.
> fix(forwarder): ignore empty files on HTTP forwarding

- apps/logwriter/template.yaml
- apps/stack/template.yaml
- cmd/subscriber/main.go
- docs/logwriter.md
- docs/stack.md
- handler/subscriber/config.go
- handler/subscriber/config_test.go
Add support for excluding log groups. Up until now we have adhered strictly to the options supported by the DescribeLogGroups API. There is no means of excluding log groups from the API response, so we implement filtering support in the client side instead. This allows us a bit more flexibility, and we can introduce regular expression support for exclusion.
> feat(logwriter): support log group exclusion

- apps/forwarder/template.yaml
- apps/stack/template.yaml
Adjust SQS retention and S3 expiration duration to match 4 days by default.
Previously, SQS retention exceeded S3 expiration, which would potentially mean that any "copy" message would fail once eventually retried.
> fix(stack): match expiration values

- .github/workflows/release.yaml
- Makefile
This commit reorders operations in order to reduce the scope for error in case of a CI failure.
We run the release job concurrently for each region. If any job fails, all other jobs are interrupted. This opened the possibility for the root `packaged.yaml` template to be uploaded, but with incorrect ACLs.
We should always copy the template with the ACL directive. This eliminates the possibility of the object existing with the incorrect permissions. Furthermore, we should only upload the template once all objects it refers to are also publicly readable. That way we ensure that if the template is accessible, it is also installable.
> ci: improve release robustness

- cmd/forwarder/main.go
- cmd/loggroupgenerator/main.go
- cmd/subscriber/main.go
Marking the root span as a service entry point makes browsing traces in UI easier.
> fix: set root span to server kind

- tracing/tracing.go
The lambda resource detector will error if executed from outside a lambda. We must gate it since we will want to use this tracing instrumentation in CLI tools.
> fix(tracing): gate lambda resource detector

- apps/forwarder/template.yaml
The IAM role of the forwarder only needs to be known when forwarding data to Filedrop. For cases where we are not pointing at an S3 data access point, we can fallback to letting Cloudformation generating a unique role name. Doing so avoids the possibility of name clashes when installing a forwarder in different regions.
> fix(forwarder): relax IAM role naming

- tracing/mux.go
We currently only handle lambda initialization as a server kind span. Intercept the lambda invocation and set as server kind too.
> fix: set server span kind on invoke

- tracing/tracing.go
We were previously only setting the lambda "version" in our instrumentation version. In practice this instrumentation is only present in our cold start trace (`realInit`). Other traces will use tracers belonging to different instrumentation libraries.
This commit introduces `service.version` as part of the resource attributes. Since the binary is rebuilt on cloudformation template changes, it should accurately track the version of the service rather than merely the "binary" version.
> fix(tracing): set service version

- cmd/forwarder/main.go
- cmd/subscriber/main.go
- go.mod
- go.sum
- tracing/mux.go
- vendor/go.opentelemetry.io/contrib/instrumentation/github.com/aws/aws-lambda-go/otellambda/LICENSE
- vendor/go.opentelemetry.io/contrib/instrumentation/github.com/aws/aws-lambda-go/otellambda/README.md
- vendor/go.opentelemetry.io/contrib/instrumentation/github.com/aws/aws-lambda-go/otellambda/config.go
- vendor/go.opentelemetry.io/contrib/instrumentation/github.com/aws/aws-lambda-go/otellambda/doc.go
- vendor/go.opentelemetry.io/contrib/instrumentation/github.com/aws/aws-lambda-go/otellambda/lambda.go
- vendor/go.opentelemetry.io/contrib/instrumentation/github.com/aws/aws-lambda-go/otellambda/version.go
- vendor/go.opentelemetry.io/contrib/instrumentation/github.com/aws/aws-lambda-go/otellambda/wrapHandler.go
- vendor/go.opentelemetry.io/contrib/instrumentation/github.com/aws/aws-lambda-go/otellambda/wrapLambdaHandler.go
- vendor/modules.txt
Wrap our existing mux instrumentation with the `otellambda` package. The upstream package sets a reasonable span name, kind, and injects attributes that are consistent with the `faas` semantic convention.
In order to attach the payload to every invocation we still need to provide our own Invoke method. The payload is added as an attribute.
> fix: introduce otellambda instrumentation

- tracing/http.go
All our HTTP requests are outbound to a remote set, so we should set the span kind to `client`.
> fix: adjust span kind for HTTP client

- tracing/http.go
- tracing/tracing.go
- tracing/tracing_test.go
In cloudformation we do not have much configuration surface area for passing in environment variables, particular for debug-only usecases such as tracing. This commit allows passing in resource attributes through query parameters for an OTEL OTLP endpoint. Since this behavior is not per-spec, we initially limit its scope to
`deployment.environment`, which is useful to disambiguate between collection environments.
> fix(tracing): allow setting resource attributes via URL

- cmd/forwarder/main.go
- tracing/aws.go
- tracing/http.go
We should set user agent as part of our tracing package, rather than relying on each top level entry point for a handler to set it up. We will rely on the OTEL service name, which is consistently set as part of each lambda config.
> fix: consistent userAgent for AWS SDK and HTTP

- tracing/mux.go
This ensures we flush data prior to lambda freezing.
> fix(tracing): set flusher in otellambda instrumentation

- apps/config/template.yaml
- docs/config.md
The AWS Config API does not allow both exclusion and inclusion sets. We currently allow users to provide both, and prefer `ExcludeResourceTypes`, which can be misleading if the intent was to restrict collection further.
This commit changes precendence to prefer `IncludeResourceTypes` over `ExcludeResourceTypes`. The reasoning here is that the inclusion list tends to be small, in which case it is the cost conservative behavior.
An alternative approach would be to assert that only one of the sets is provided. Unfortunately errors in cloudformation are hard to debug, so the user experience would be terrible.
> fix(config): adjust precedence of parameters.

- pkg/handler/forwarder/override/presets/aws/v1.yaml
- pkg/handler/forwarder/override/presets_test.go
We currently rely on the S3 object being written with the correct content-encoding. There are many cases, such as `vpcflowlogs`, where the content-type is set to `gz` and the content-encoding is left blank.
This commit ensures we always set the content-encoding correctly for filenames that end in `.gz`
> fix(forwarder): set content-encoding on override

- apps/forwarder/template.yaml
- integration/tests/forwarder.tftest.hcl
We previously triggered the forwarder lambda on all S3 object created events, and relied on the lambda to ignore spurious triggers. This turns out to be too lax. We can filter events by source bucket using the `wildcard` pattern. Like bucket names, the wildcard pattern supports globs. Without globs, it behaves as an exact match. This means that for source bucket names `foo*` and `bar`, the event bridge pattern compiled would be:
```
{
"source": ["aws.s3"],
"detail-type": ["Object Created"],
"detail.bucket.name": [{
"wildcard": "foo*"
},
{
"wildcard": "bar"
}
]
}
```
> fix(forwarder): filter eventbridge triggers by source bucket

- apps/forwarder/template.yaml
- docs/forwarder.md
- integration/tests/forwarder_s3.tftest.hcl
- pkg/handler/forwarder/config.go
- pkg/handler/forwarder/config_test.go
- pkg/handler/forwarder/filter.go
- pkg/handler/forwarder/handler.go
- pkg/handler/forwarder/handler_test.go
- pkg/lambda/forwarder/lambda.go
This commit adds the ability to specify a set of patterns which identify object keys we are willing to forward.
A new parameter, `SourceObjectKeys`, allows specifying a set of key patterns against which incoming objects are filtered. We also use this parameter to further constrict our eventbridge pattern for triggering the lambda function.
> feat(forwarder): add `SourceObjectKeys`

- pkg/handler/forwarder/config.go
- pkg/handler/forwarder/handler.go
- pkg/handler/forwarder/handler_test.go
- pkg/lambda/forwarder/lambda.go
The forwarder function processes SQS tasks concurrently. By default this value was previously unbounded, which would cause significant delay when redriving a Dead Letter Queue.
This commit changes the default to be set to the runtime number of CPUs, which allows the behaviour to scale with the amount of memory allocated to the lambda function.
> fix(forwarder): cap number of concurrency SQS tasks

- apps/logwriter/template.yaml
- apps/stack/template.yaml
`LogGroupNamePatterns` and `LogGroupNamePrefixes` do not support regular expressions. Constraining the allowed pattern for either parameter ensures we error out early if a user attempts to pass in a regular expression.
> fix(logwriter): tighten up parameter patterns

- apps/logwriter/template.yaml
- docs/logwriter.md
- integration/tests/logwriter.tftest.hcl
- integration/tests/stack.tftest.hcl
- pkg/handler/subscriber/cloudformation.go
- pkg/lambda/subscriber/lambda.go
- vendor/github.com/aws/aws-lambda-go/cfn/README.md
- vendor/github.com/aws/aws-lambda-go/cfn/event.go
- vendor/github.com/aws/aws-lambda-go/cfn/response.go
- vendor/github.com/aws/aws-lambda-go/cfn/wrap.go
- vendor/modules.txt
It is common practice to iteratively adjust parameters in the logwriter stack and refine filters through trial and error. Previously, log discovery and subscription would only run once our scheduler fired. This commit additionally ensures we manually trigger the lambda on any parameter change to our CloudFormation stack.
The commit adds:
- a custom resource to our CloudFormation logwriter stack which embeds all parameters. Any change to our input parameters will generate a CloudFormation event which triggers the subscriber Lambda function.
- a handler to the subscriber Lambda function which processes CloudFormation events. On stack updates, we will initiate a discovery request. We do not need to do any handling on install, since the scheduler will fire on first time install.
- a step to …
> fix(logwriter): trigger on update

- apps/stack/template.yaml
fix to correct logs to work when subscriber is not enabled
> fix: OB-38134 make parent stack outputs conditioned on nested stack

- static/cloudwatchmetrics/filters/recommended.yaml
Adding `DatabaseConnections` as an included metrics.  Needed for RDS Instance Dashboard in AWS-Quickstart
> fix: update recommended.yaml to include DatabaseConnections

- apps/forwarder/template.yaml
- apps/logwriter/template.yaml
- apps/metricstream/template.yaml
This should provide no functional difference, simply bumps us to latest and greatest.
> feat: bump runtime to provided.al2023

- apps/metricstream/template.yaml
- apps/stack/template.yaml
- docs/metricstream.md
- docs/stack.md
This makes updates to the docs, and also the comment under the input fields in the cloudformation stack creation page.
> docs: clarify when filterUri is overridden

- .github/workflows/integration.yaml
- pkg/handler/forwarder/override/presets/infer/v1.yaml
Update regex to match gzipped files correctly. 
The `forwarder` regex was matching any file ending in `gz` and updating the `content-encoding` to `gzip`.
> fix: Update regex to match gzipped files correctly. 

- .github/workflows/orca.yaml
- Allows pushing of key `aws-sam-apps` binary image to ECR for Orca scanning 
- See comment: https://observe.atlassian.net/browse/CS-2416?focusedCommentId=266495
> chore: add ecr image push for orca

- .github/workflows/orca.yaml
- Change workflow for container scan to only run on pushes to main
- Pushes to main should create a new "release" of docker image which is what we want scanned. 
- Currently the sha256 changes upon every single run of the same branch (no code or binary changes). 
- Because of above, running this on a schedule causes the docker image SHA to change in ECR (which deletes the old asset and it's alerts) 
Problematic asset override:
> chore: orca workflow on push to main

- .github/workflows/orca.yaml
- Dockerfile.all-binaries
- Makefile
- push-to-ecr.sh
Followup from this PR: https://github.com/observeinc/aws-sam-apps/pull/394
and addresses this ticket correctly: https://observe.atlassian.net/browse/OB-45637
Tested to use cache correctly and not override previous ECR images! 
Pinned to 12:44pm even though we have pushed many times. This is what orca requires for consistent scanning and to avoid redundant alert generations.
> chore: update orca workflow to support image caching for SHA reproducibility

- .github/workflows/orca-ecr-release.yaml
- .github/workflows/orca.yaml
- Caching doesn't work properly if workflow fails (regardless of forced github action steps)
- Separating out orca scan from ECR image push (so failure of scan doesn't affect caching steps)
We need:
```
Post job cleanup.
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/aws-sam-apps/aws-sam-apps --files-from manifest.txt --use-compress-program zstdmt
Sent 38310[2](https://github.com/observeinc/aws-sam-apps/actions/runs/15147503667/job/42586651974#step:12:2)50 of 38310250 (100.0%), 41.1 MBs/sec
Cache saved with key: Linux-buildx-refs/heads/nikhil/separate-image-build-steps-146bac5b614ce854162a0894c4c6b53fe937880e
``` 
See example of failures (post-docker save cache step doesn't register)
> chore: separate out orca workflows

- .gitignore
- apps/metricstream/template.yaml
- apps/stack/template.yaml
- cmd/testing/forwarderhttp/main.go
- pkg/handler/forwarder/handler.go
- pkg/handler/forwarder/s3http/client.go
- pkg/handler/forwarder/s3http/config_test.go
- pkg/handler/forwarder/s3http/internal/batch/runner_test.go
- pkg/handler/forwarder/s3http/internal/decoders/csv.go
- pkg/handler/forwarder/s3http/internal/decoders/decoder_test.go
- pkg/handler/forwarder/s3http/internal/decoders/wrapper.go
- pkg/handler/forwarder/s3http/internal/request/handler.go
- pkg/handler/forwarder/s3http/internal/request/handler_test.go
- pkg/handler/metricsconfigurator/handler.go
- pkg/handler/subscriber/instrument.go
- pkg/handler/subscriber/request_test.go
- pkg/lambda/env.go
Update build tests
• Fixed unchecked error returns for `os.Remove`, `getResp.Body.Close`, `file.Close`, `gr.Close`, `resp.Body.Close`, `r.Body.Close`, and `os.Setenv` as reported by `errcheck` linter.
• Addressed `staticcheck` `QF1008` issues by removing unnecessary embedded field selectors in multiple packages.
• Ensured latest `golangci/golangci-lint` run issues are resolved.
• Added `cfn-lint` to `metadata`, to `ignore_checks` to resolve `[[W1030: Validate the values that come from a Ref function] ({'Ref': 'GQLToken'} is shorter than 1 when 'Ref' is resolved) matched 327]` during `Validate SAM templates` in build tests.
• Ran all integration tests via `make test-integration`
• Manually ran `sam deploy` to validate apps continue to function.
> build(deps): Update build tests OB-46206
